# Generated by Django 4.2 on 2023-07-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gasolina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('litros_vendidos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_litro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
